### ISSUE TITLE
[Documentation] Would it be possible to add a short explanation how this magic works with cmd.exe?

### ISSUE THREAD

**Issue by rubyFeedback** [andrecarlucci/fix#1]
Would it be possible to add a short explanation how this magic works with cmd.exe? E. g. to the main README if
possible. Thank you for reading this issue request and perhaps considering.

**Comment by andrecarlucci** [comment]
Hi @rubyFeedback, thanks for the request.
I just added some info in the main README, could you check and report back if the explanation is good enough?
Cheers!
